import FirebaseComponents from "@/components/firebase-components"
import Link from "next/link"
import CheckUser from "./check-user"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <FirebaseComponents>
          <nav>
            <ul>
              <li><Link href="/sign-up">Sign up</Link></li>
              <li><Link href="/sign-in">Sign in</Link></li>
            </ul>
          </nav>
          <CheckUser>
            {children}
          </CheckUser>
        </FirebaseComponents>
      </body>
    </html>
  )
}
