import FirebaseComponents from "@/components/firebase-components"
import BumpUnauthorised from "./bump-unauthorised"
import Nav from "./nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <FirebaseComponents>
          <BumpUnauthorised>
            <Nav/>
            {children}
          </BumpUnauthorised>
        </FirebaseComponents>
      </body>
    </html>
  )
}
