#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm exec lint-staged

#if (( $(git diff | awk 'END {print NR}') > 0 )); then echo 'You must commit all your changes.'; exit 1; fi
if (( $(git diff --cached | awk 'END {print NR}') > 99 )); then echo 'SMALL COMMITS ONLY!!! git diff cannot be longer than 100 lines'; exit 1; fi
