#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm exec lint-staged

if (( $(git diff --cached | awk 'END {print NR}') > 99 )); then echo 'SMALL COMMITS ONLY!!! git diff cannot be longer than 100 lines'; exit 1; fi
